spring:
  application:
    name: serviceb
  config:
    import: "optional:configserver:"
  cloud:
    config: 
      uri: http://localhost:8888/
      name: service-b
      enable: false
  profiles:
    active: dev
